INSERT INTO orchid (orchid) VALUES ('Phalaenopsis');
INSERT INTO orchid (orchid) VALUES ('Cambria-like');
INSERT INTO orchid (orchid) VALUES ('Cattleya');
INSERT INTO orchid (orchid) VALUES ('Cymbidium');
INSERT INTO orchid (orchid) VALUES ('Dendrobium');
INSERT INTO orchid (orchid) VALUES ('Dendrobium Nobilé');
INSERT INTO orchid (orchid) VALUES ('Miltonia');
INSERT INTO orchid (orchid) VALUES ('Oncidium');
INSERT INTO orchid (orchid) VALUES ('Paphiopedilum');
INSERT INTO orchid (orchid) VALUES ('Vanda');
INSERT INTO orchid (orchid) VALUES ('Zygopetalum');
INSERT INTO orchid (orchid) VALUES ('Garden');
INSERT INTO orchid (orchid) VALUES ('Calanthe');
INSERT INTO orchid (orchid) VALUES ('Bletila');
INSERT INTO orchid (orchid) VALUES ('Cypripedium');
INSERT INTO orchid (orchid) VALUES ('Pleione');
INSERT INTO orchid (orchid) VALUES ('Epipactis');
INSERT INTO orchid (orchid) VALUES ('Ladys Slipper');
INSERT INTO orchid (orchid) VALUES ('Slipper');
INSERT INTO orchid (orchid) VALUES ('Moth');
INSERT INTO orchid (orchid) VALUES ('Tiger');
INSERT INTO orchid (orchid) VALUES ('Pansy');